title: Look!
theme: minima
author: sonder-cha
email: 1967741644zht@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
